import {
  UserProfile,
  Course,
  Quiz,
  LibraryResource,
  Announcement,
  CompetencyMapping,
  QuizSubmission,
} from "@/types";

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: "admin-1",
    email: "dg.meteorology@imd.gov.in",
    displayName: "Dr. M. Mohapatra",
    role: "admin",
    status: "approved",
    emailVerified: true,
    department: "Executive Directorate / DG Office",
    designation: "Director General of Meteorology",
    location: "Mausam Bhavan, New Delhi",
    phoneNumber: "+91-11-24611060",
    qualifications: [
      {
        id: "q-1",
        degree: "Ph.D. in Meteorology",
        institution: "IIT Delhi",
        year: "1998",
        specialization: "Tropical Cyclones & Severe Weather Forecasting",
      },
      {
        id: "q-2",
        degree: "M.Sc. in Physics",
        institution: "Utkal University",
        year: "1988",
        specialization: "Atmospheric Sciences",
      },
    ],
    experience: [
      {
        id: "e-1",
        designation: "Director General",
        organization: "India Meteorological Department (MoES)",
        station: "New Delhi HQ",
        years: 32,
      },
    ],
    skills: ["Cyclone Warning Systems", "Disaster Management", "Policy Formulation", "Numerical Weather Prediction"],
    interests: ["Early Warning Systems", "Climate Resilience", "Public Weather Services"],
    certificates: [],
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    uid: "trainer-1",
    email: "rs.sharma@imd.gov.in",
    displayName: "Dr. R. S. Sharma",
    role: "trainer",
    status: "approved",
    emailVerified: true,
    department: "Radar & Severe Weather Division",
    designation: "Scientist-F & Head of Radar Operations",
    location: "IMD Pune Training Centre",
    phoneNumber: "+91-20-25535201",
    qualifications: [
      {
        id: "q-3",
        degree: "Ph.D. in Radar Meteorology",
        institution: "Pune University / IMD",
        year: "2006",
        specialization: "Doppler Radar Dual-Polarization Algorithms",
      },
    ],
    experience: [
      {
        id: "e-2",
        designation: "Lead Instructor - Radar Met",
        organization: "Central Training Institute (CTI) Pune",
        station: "IMD Pune",
        years: 18,
      },
    ],
    skills: ["Doppler Weather Radar (DWR)", "Dual-Pol Products", "Hydrometeor Classification", "Python for Met"],
    interests: ["Nowcasting", "Thunderstorm Dynamics", "Radar Data Assimilation"],
    certificates: [],
    createdAt: "2024-01-12T11:30:00Z",
  },
  {
    uid: "trainer-2",
    email: "somenath.dutta@imd.gov.in",
    displayName: "Dr. Somenath Dutta",
    role: "trainer",
    status: "approved",
    emailVerified: true,
    department: "Numerical Weather Prediction (NWP)",
    designation: "Scientist-G",
    location: "Mausam Bhavan, New Delhi",
    phoneNumber: "+91-11-24651122",
    qualifications: [
      {
        id: "q-4",
        degree: "Ph.D. in Atmospheric Dynamics",
        institution: "Jadavpur University",
        year: "2001",
        specialization: "Mountain Waves & NWP Parameterization",
      },
    ],
    experience: [
      {
        id: "e-3",
        designation: "Principal Researcher & Trainer",
        organization: "India Meteorological Department",
        station: "New Delhi",
        years: 24,
      },
    ],
    skills: ["WRF Model", "GFS High-Resolution Modeling", "Fortran/Python", "Data Assimilation"],
    interests: ["Mesoscale Modeling", "Monsoon Depressions", "High Performance Computing"],
    certificates: [],
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    uid: "trainee-1",
    email: "sk.verma@imd.gov.in",
    displayName: "S. K. Verma",
    role: "trainee",
    status: "approved",
    emailVerified: true,
    department: "Regional Meteorological Centre",
    designation: "Scientific Officer",
    location: "RMC Kolkata, West Bengal",
    phoneNumber: "+91-33-24793782",
    qualifications: [
      {
        id: "q-5",
        degree: "M.Sc. in Atmospheric Sciences",
        institution: "Calcutta University",
        year: "2020",
        specialization: "Physical Meteorology",
      },
    ],
    experience: [
      {
        id: "e-4",
        designation: "Scientific Officer",
        organization: "IMD RMC Kolkata",
        station: "Alipore Observatory",
        years: 4,
      },
    ],
    skills: ["Synoptic Analysis", "Surface Observations", "Satellite Interpretation"],
    interests: ["Severe Thunderstorms (Kalbaisakhi)", "Bay of Bengal Cyclones"],
    certificates: [
      {
        id: "cert-1",
        courseId: "course-1",
        courseTitle: "Advanced Doppler Weather Radar Operations & Product Interpretation",
        issueDate: "2024-08-15",
        verificationCode: "MOES-IMD-2024-DWR-9482",
        grade: "Distinction",
        scorePercentage: 92,
      },
    ],
    createdAt: "2024-02-01T14:20:00Z",
  },
  {
    uid: "trainee-2",
    email: "ananya.sen@imd.gov.in",
    displayName: "Ananya Sen",
    role: "trainee",
    status: "approved",
    emailVerified: true,
    department: "Coastal Radar Station",
    designation: "Meteorologist Gr-II",
    location: "Paradip DWR Station, Odisha",
    phoneNumber: "+91-6722-220199",
    qualifications: [
      {
        id: "q-6",
        degree: "B.Tech in Electronics & Communication",
        institution: "NIT Rourkela",
        year: "2021",
        specialization: "RF & Signal Processing",
      },
    ],
    experience: [
      {
        id: "e-5",
        designation: "Meteorologist Gr-II",
        organization: "IMD Coastal Operations",
        station: "Paradip Observatory",
        years: 3,
      },
    ],
    skills: ["Radar Hardware Maintenance", "Signal Processing", "RF Calibration"],
    interests: ["Cyclone Tracking", "Maritime Warnings"],
    certificates: [],
    createdAt: "2024-02-10T16:00:00Z",
  },
  {
    uid: "trainee-3",
    email: "rajesh.patel@imd.gov.in",
    displayName: "Rajesh Patel",
    role: "trainee",
    status: "pending",
    emailVerified: false,
    department: "Agro-Meteorological Advisory Unit",
    designation: "Scientific Assistant",
    location: "AMFU Anand, Gujarat",
    phoneNumber: "+91-2692-261310",
    qualifications: [
      {
        id: "q-7",
        degree: "B.Sc. in Agriculture",
        institution: "Anand Agricultural University",
        year: "2022",
        specialization: "Agro-meteorology",
      },
    ],
    experience: [
      {
        id: "e-6",
        designation: "Scientific Assistant",
        organization: "Gramin Krishi Mausam Sewa (GKMS)",
        station: "Anand Station",
        years: 2,
      },
    ],
    skills: ["Agromet Advisory Preparation", "Soil Moisture Indices", "Crop Weather Calendar"],
    interests: ["Farmers Outreach", "Drought Monitoring"],
    certificates: [],
    createdAt: "2024-03-01T10:15:00Z",
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: "course-1",
    code: "MET-401",
    title: "Advanced Doppler Weather Radar Operations & Product Interpretation",
    domain: "Radar Meteorology",
    description:
      "Comprehensive training covering S-band and X-band Doppler Weather Radars (DWR), dual-polarization moments (Zdr, Kdp, RhoHV), hydrometeor classification, dealiasing radial velocities, and quantitative precipitation estimation (QPE) for severe weather nowcasting.",
    trainerId: "trainer-1",
    trainerName: "Dr. R. S. Sharma",
    durationHours: 36,
    level: "Advanced",
    syllabus: [
      "Fundamentals of Radar Meteorology & Radar Equation",
      "Doppler Principles: Radial Velocity, Nyquist Limit & Velocity Dealiasing",
      "Dual-Polarization Moments & Hydrometeor Identification (HCA)",
      "Nowcasting Convective Storms, Tornadoes, and Hail Signatures",
      "Operational DWR Maintenance, Calibration, and Sun-tracking checks",
    ],
    enrolledTraineeIds: ["trainee-1", "trainee-2"],
    rating: 4.9,
    reviewsCount: 28,
    thumbnailUrl: "https://images.unsplash.com/photo-1590055531615-f16d36ffe8ec?w=600&q=80",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "course-2",
    code: "MET-502",
    title: "High-Resolution Numerical Weather Prediction (WRF & Global Models)",
    domain: "Numerical Modeling",
    description:
      "Hands-on operational training in setting up, configuring, and analyzing high-resolution Weather Research and Forecasting (WRF) models. Covers physical parameterizations, initial and boundary condition processing, and post-processing with Python.",
    trainerId: "trainer-2",
    trainerName: "Dr. Somenath Dutta",
    durationHours: 42,
    level: "Advanced",
    syllabus: [
      "Atmospheric Governing Equations & Numerical Discretization",
      "WPS (Geogrid, Ungrib, Metgrid) Pre-processing Workflows",
      "Convective, Microphysics, and Planetary Boundary Layer (PBL) Schemes",
      "Data Assimilation of Satellite Radiance and Radar Radial Velocity",
      "Ensemble Prediction Systems (EPS) and Verification Metrics",
    ],
    enrolledTraineeIds: ["trainee-1"],
    rating: 4.8,
    reviewsCount: 34,
    thumbnailUrl: "https://images.unsplash.com/photo-1507499739999-097706ad8914?w=600&q=80",
    createdAt: "2024-01-25T11:00:00Z",
  },
  {
    id: "course-3",
    code: "MET-303",
    title: "Satellite Meteorology: INSAT-3D/3DR/3DS Multi-Spectral Interpretation",
    domain: "Satellite Meteorology",
    description:
      "Operational exploitation of India's geostationary meteorological satellites. Master thermal infrared, water vapor, and visible imagery analysis, cloud-top temperatures, Rapid Scan imaging, and convective cloud tracking.",
    trainerId: "trainer-1",
    trainerName: "Dr. R. S. Sharma",
    durationHours: 30,
    level: "Intermediate",
    syllabus: [
      "Orbits, Payloads, and Sensor Spectral Channels of INSAT-3DS",
      "Identification of Weather Systems: Monsoons, Western Disturbances, ITCZ",
      "Upper-level Jet Streams and Moisture Channel Interpretation",
      "Quantitative Products: Atmospheric Motion Vectors (AMVs), Outgoing Longwave Radiation (OLR)",
      "Satellite-Based Cyclone Intensity Estimation via Dvorak Method",
    ],
    enrolledTraineeIds: ["trainee-2"],
    rating: 4.7,
    reviewsCount: 22,
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
    createdAt: "2024-02-05T09:30:00Z",
  },
  {
    id: "course-4",
    code: "MET-204",
    title: "Agrometeorological Advisory Services (AAS) & FASAL Crop Modeling",
    domain: "Agro-Meteorology",
    description:
      "Equipping field officers to generate district and block-level agromet bulletins, compute Standardized Precipitation Indices (SPI), assess pest/disease risks from weather forecasts, and interface with farmers through the Meghdoot App.",
    trainerId: "trainer-2",
    trainerName: "Dr. Somenath Dutta",
    durationHours: 24,
    level: "Basic",
    syllabus: [
      "Agro-climatic Zones of India and Crop-Weather Calendars",
      "District-Level Medium Range Weather Forecasting Guidelines",
      "Preparation of Agromet Advisory Bulletins (AAS) for GKMS Scheme",
      "Drought Indices: SPI, SPEI, and Soil Moisture Water Balance",
      "Digital Dissemination via Meghdoot Mobile Application and KVKs",
    ],
    enrolledTraineeIds: [],
    rating: 4.9,
    reviewsCount: 19,
    thumbnailUrl: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80",
    createdAt: "2024-02-12T14:00:00Z",
  },
  {
    id: "course-5",
    code: "MET-605",
    title: "Tropical Cyclone Warning Systems & Disaster Early Warning Protocol",
    domain: "Cyclone Forecasting",
    description:
      "End-to-end operational protocol for monitoring, track prediction, landfall point determination, storm surge modeling, and dissemination of 4-stage cyclone alerts to disaster managers.",
    trainerId: "trainer-1",
    trainerName: "Dr. R. S. Sharma",
    durationHours: 32,
    level: "Advanced",
    syllabus: [
      "Cyclogenesis over North Indian Ocean (Bay of Bengal & Arabian Sea)",
      "Dvorak Technique: T-Number Analysis & Central Dense Overcast (CDO)",
      "Multi-model Ensemble Track and Intensity Guidance",
      "IIT-D Storm Surge Model Execution and Inundation Maps",
      "Standard Operating Procedures (SOP) for State Chief Secretaries and NDMA",
    ],
    enrolledTraineeIds: ["trainee-1"],
    rating: 5.0,
    reviewsCount: 41,
    thumbnailUrl: "https://images.unsplash.com/photo-1527482797697-8795b05a13fe?w=600&q=80",
    createdAt: "2024-02-18T16:00:00Z",
  },
];

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: "quiz-1",
    courseId: "course-1",
    courseTitle: "Advanced Doppler Weather Radar Operations",
    title: "Module 1 Assessment: Doppler Principles & Dual-Pol Interpretation",
    description: "Evaluates your understanding of Nyquist velocity limits, velocity dealiasing, and dual-polarization parameters (Zdr, Kdp, RhoHV).",
    durationMinutes: 15,
    deadline: "2026-11-30T23:59:59Z",
    passingScore: 70,
    createdBy: "trainer-1",
    createdByName: "Dr. R. S. Sharma",
    createdAt: "2024-03-01T10:00:00Z",
    questions: [
      {
        id: 1,
        questionText: "What occurs when the radial velocity of a storm exceeds the Nyquist velocity (Vmax) of the Doppler radar?",
        options: [
          "The radar transmitter shuts down automatically",
          "Velocity aliasing occurs, causing high velocities to wrap around with opposite sign",
          "Reflectivity values (dBZ) increase exponentially",
          "The beam attenuates completely within 10 km",
        ],
        correctOptionIndex: 1,
        explanation:
          "When a target's true radial velocity exceeds the maximum unambiguous velocity (Nyquist limit Vmax = PRF * lambda / 4), velocity aliasing (folding) occurs, causing incoming winds to appear as outgoing or vice-versa.",
      },
      {
        id: 2,
        questionText: "Which dual-polarization radar parameter is most effective in differentiating meteorological hydrometeors from biological scatterers (birds, insects) and non-meteorological ground clutter?",
        options: [
          "Differential Reflectivity (Zdr)",
          "Specific Differential Phase (Kdp)",
          "Cross-Correlation Coefficient (RhoHV)",
          "Radial Doppler Velocity (Vr)",
        ],
        correctOptionIndex: 2,
        explanation:
          "Correlation Coefficient (RhoHV) measures the consistency of horizontal and vertical backscatter signatures. Meteorological targets usually exhibit RhoHV > 0.95 (rain > 0.98), whereas non-meteorological clutter drops sharply below 0.85.",
      },
      {
        id: 3,
        questionText: "A radar reflectivity core exceeds 60 dBZ with a Differential Reflectivity (Zdr) near zero or slightly negative at mid-levels. What weather phenomenon does this signature strongly indicate?",
        options: [
          "Heavy stratiform drizzle",
          "Dry giant hail aloft",
          "Clear air turbulence",
          "Marine fog",
        ],
        correctOptionIndex: 1,
        explanation:
          "Very high reflectivity (>= 60 dBZ) paired with near-zero or negative Zdr indicates large, tumbling, non-spherical hail stones that backscatter equally or horizontally attenuated.",
      },
      {
        id: 4,
        questionText: "In Doppler radar terminology, what is the 'Doppler Dilemma'?",
        options: [
          "The trade-off between radar antenna weight and rotation speed",
          "The inverse relationship between maximum unambiguous range (Rmax) and maximum unambiguous velocity (Vmax)",
          "The conflict between S-band and C-band radar frequencies",
          "The mismatch between analog calibration and digital signal display",
        ],
        correctOptionIndex: 1,
        explanation:
          "Because Rmax = c / (2 * PRF) and Vmax = (lambda * PRF) / 4, increasing PRF increases unambiguous velocity but proportionally reduces unambiguous range (Rmax * Vmax = c * lambda / 8).",
      },
      {
        id: 5,
        questionText: "Why does the India Meteorological Department predominantly utilize S-band (2.7 - 3.0 GHz) Doppler Radars along India's cyclone-prone eastern coastline?",
        options: [
          "S-band radar components are cheaper to manufacture",
          "S-band radar wavelengths experience substantially lower precipitation attenuation in severe tropical cyclones than C-band or X-band",
          "S-band radomes do not require cooling systems",
          "S-band frequencies are exempt from ITU frequency licensing",
        ],
        correctOptionIndex: 1,
        explanation:
          "S-band (10 cm wavelength) experiences minimal atmospheric attenuation compared to C-band (5 cm) and X-band (3 cm), allowing the radar beam to penetrate deep into torrential cyclone rainbands without losing the core signal.",
      },
    ],
  },
  {
    id: "quiz-2",
    courseId: "course-2",
    courseTitle: "High-Resolution Numerical Weather Prediction (WRF)",
    title: "Mid-Term Examination: Model Dynamics & Parameterization Schemes",
    description: "Covers WRF WPS processing, non-hydrostatic governing equations, and convective boundary layer schemes.",
    durationMinutes: 20,
    deadline: "2026-12-15T23:59:59Z",
    passingScore: 70,
    createdBy: "trainer-2",
    createdByName: "Dr. Somenath Dutta",
    createdAt: "2024-03-05T14:00:00Z",
    questions: [
      {
        id: 1,
        questionText: "At what grid spacing does the hydrostatic assumption break down, necessitating a non-hydrostatic dynamical core such as the WRF-ARW?",
        options: [
          "Grid resolutions coarser than 50 km",
          "Grid resolutions finer than approximately 10 km",
          "Only at oceanic sea level",
          "Only in the stratosphere above 10 hPa",
        ],
        correctOptionIndex: 1,
        explanation:
          "When horizontal grid spacing drops below ~10 km, vertical accelerations become comparable in magnitude to the vertical pressure gradient and gravity forces, requiring non-hydrostatic formulations.",
      },
      {
        id: 2,
        questionText: "In the WRF Preprocessing System (WPS), which program is responsible for interpolating terrestrial static datasets (terrain height, land use, soil categories) onto the computational model domain?",
        options: ["Ungrib.exe", "Geogrid.exe", "Metgrid.exe", "Real.exe"],
        correctOptionIndex: 1,
        explanation:
          "Geogrid.exe defines the model simulation domains and interpolates static geographical datasets (topography, albedo, vegetation, land use categories) onto the grid.",
      },
      {
        id: 3,
        questionText: "Why should cumulus convective parameterization schemes (e.g., Kain-Fritsch) typically be disabled when running WRF simulations at cloud-resolving grid resolutions of 3 km or less?",
        options: [
          "The compiler will throw a segmentation fault",
          "At resolutions <= 3 km, deep convective updrafts and downdrafts are explicitly resolved by the model dynamics and microphysics",
          "Moisture will fail to condense",
          "Solar radiation code will become unstable",
        ],
        correctOptionIndex: 1,
        explanation:
          "At cloud-resolving scales (<= 3-4 km), convective circulations are explicitly simulated on the grid mesh, so parameterized cumulus schemes lead to double-counting convection.",
      },
    ],
  },
];

export const INITIAL_SUBMISSIONS: QuizSubmission[] = [
  {
    id: "sub-1",
    quizId: "quiz-1",
    quizTitle: "Module 1 Assessment: Doppler Principles & Dual-Pol Interpretation",
    courseId: "course-1",
    traineeId: "trainee-1",
    traineeName: "S. K. Verma",
    score: 5,
    totalQuestions: 5,
    percentage: 100,
    passed: true,
    submittedAt: "2024-08-14T15:42:00Z",
    answers: [
      { questionId: 1, selectedOption: 1, isCorrect: true },
      { questionId: 2, selectedOption: 2, isCorrect: true },
      { questionId: 3, selectedOption: 1, isCorrect: true },
      { questionId: 4, selectedOption: 1, isCorrect: true },
      { questionId: 5, selectedOption: 1, isCorrect: true },
    ],
  },
];

export const INITIAL_RESOURCES: LibraryResource[] = [
  {
    id: "res-1",
    courseId: "course-1",
    courseTitle: "Advanced Doppler Weather Radar Operations",
    title: "Lecture 01: Dual-Polarization Radar Moments & HydroClass Algorithms",
    type: "video",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    uploadedBy: "trainer-1",
    uploadedByName: "Dr. R. S. Sharma",
    uploadedAt: "2024-02-10T10:00:00Z",
    sizeOrDuration: "45 mins",
    description: "Detailed video lecture explaining differential reflectivity (Zdr) and correlation coefficient (RhoHV) with real storm case studies from IMD Delhi and Kolkata radars.",
  },
  {
    id: "res-2",
    courseId: "course-1",
    courseTitle: "Advanced Doppler Weather Radar Operations",
    title: "IMD Standard Operating Procedure (SOP): DWR Calibration & Sun Tracking Protocol",
    type: "manual",
    url: "https://imdpune.gov.in/sop_dwr_calibration_v4.pdf",
    uploadedBy: "trainer-1",
    uploadedByName: "Dr. R. S. Sharma",
    uploadedAt: "2024-02-12T11:30:00Z",
    sizeOrDuration: "4.8 MB (PDF)",
    description: "Official MoES/IMD technical manual outlining weekly and pre-monsoon calibration steps, sun-tracking alignments, and transmitter power monitoring.",
  },
  {
    id: "res-3",
    courseId: "course-1",
    courseTitle: "Advanced Doppler Weather Radar Operations",
    title: "Presentation Slides: Convective Storm Nowcasting & Tornado Vortex Signatures (TVS)",
    type: "presentation",
    url: "https://imdpune.gov.in/slides_convective_nowcasting.pptx",
    uploadedBy: "trainer-1",
    uploadedByName: "Dr. R. S. Sharma",
    uploadedAt: "2024-02-14T09:15:00Z",
    sizeOrDuration: "28 Slides (PPTX)",
    description: "Comprehensive lecture slide deck covering mesocyclone detection, hook echo identification, and VIL (Vertically Integrated Liquid) thresholds.",
  },
  {
    id: "res-4",
    courseId: "course-2",
    courseTitle: "High-Resolution Numerical Weather Prediction (WRF)",
    title: "Lecture 04: Setting up WPS Domains & WRF Physics Parameterizations",
    type: "video",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    uploadedBy: "trainer-2",
    uploadedByName: "Dr. Somenath Dutta",
    uploadedAt: "2024-02-20T14:00:00Z",
    sizeOrDuration: "58 mins",
    description: "Step-by-step walkthrough in Linux HPC environment configuring namelist.wps and namelist.input for monsoon depression simulations.",
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Urgent Circular: Mandatory Annual Cyclone Season Refresher Training Starting Nov 15",
    category: "urgent_notice",
    priority: "high",
    content:
      "All Regional Meteorological Centres (Chennai, Kolkata, Mumbai, New Delhi, Guwahati, Nagpur) and coastal radar observatories are directed to ensure all duty officers complete MET-605 and MET-401 certification prior to the post-monsoon cyclone season.",
    publishedBy: "Dr. M. Mohapatra (DG IMD)",
    publishedAt: "2024-10-01T09:00:00Z",
  },
  {
    id: "ann-2",
    title: "Departmental Achievement: 140 Scientific Officers Certified in Advanced Doppler Radar Operations",
    category: "achievement",
    priority: "normal",
    content:
      "Under the MoES Capacity Building Scheme, 140 meteorologists and scientific assistants across 35 DWR stations have successfully cleared national competency assessments with an average score of 88.4%.",
    publishedBy: "Training Division, Mausam Bhavan",
    publishedAt: "2024-09-25T11:30:00Z",
  },
  {
    id: "ann-3",
    title: "Newly Added Course Spotlight: INSAT-3DS Multi-Spectral Interpretation (MET-303)",
    category: "course_spotlight",
    priority: "normal",
    content:
      "A new specialized training module on utilizing data from India's recently operational INSAT-3DS meteorological satellite has been published by the Satellite Meteorology Division. Trainees can self-enroll now.",
    publishedBy: "Admin Office",
    publishedAt: "2024-09-20T14:15:00Z",
  },
];

export const INITIAL_COMPETENCY_MAPPINGS: CompetencyMapping[] = [
  {
    id: "comp-1",
    subject: "Doppler Weather Radar Maintenance & Dual-Polarization Calibration",
    domain: "Radar Meteorology",
    requiredSkills: ["Doppler Weather Radar (DWR)", "Dual-Pol Products", "RF Calibration", "Signal Processing"],
    minExperienceYears: 8,
    recommendedTrainerIds: ["trainer-1"],
    description: "Specialized capacity building for maintaining S/C/X-band radar hardware, transmitter tubes, waveguide antennas, and dual-pol bias calibration.",
  },
  {
    id: "comp-2",
    subject: "High-Performance Numerical Weather Prediction & Data Assimilation",
    domain: "Numerical Modeling",
    requiredSkills: ["WRF Model", "GFS High-Resolution Modeling", "Fortran/Python", "Data Assimilation"],
    minExperienceYears: 10,
    recommendedTrainerIds: ["trainer-2"],
    description: "Training meteorologists on HPC supercomputing cluster operations, 3D-Var/4D-Var data assimilation, and WRF ensemble modeling.",
  },
  {
    id: "comp-3",
    subject: "Satellite-Based Tropical Cyclone Dvorak Technique & Track Forecasting",
    domain: "Cyclone Forecasting",
    requiredSkills: ["Cyclone Warning Systems", "Satellite Interpretation", "Dvorak Method", "Synoptic Analysis"],
    minExperienceYears: 12,
    recommendedTrainerIds: ["admin-1", "trainer-1"],
    description: "Advanced competency development in subjective and automated Dvorak T-number estimation and storm surge advisory generation.",
  },
  {
    id: "comp-4",
    subject: "Gramin Krishi Mausam Sewa (GKMS) Block-Level Advisory Generation",
    domain: "Agro-Meteorology",
    requiredSkills: ["Agromet Advisory Preparation", "Soil Moisture Indices", "Crop Weather Calendar"],
    minExperienceYears: 5,
    recommendedTrainerIds: ["trainer-2"],
    description: "Preparing field staff to interpret medium-range ensemble weather forecasts and generate actionable agricultural advice for farmers.",
  },
];
