import {
  UserProfile,
  Course,
  Quiz,
  LibraryResource,
  Announcement,
  CompetencyMapping,
  QuizSubmission,
} from "@/types";

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: "admin-1",
    email: "admin@capacityconnect.in",
    displayName: "Platform Admin",
    role: "admin",
    status: "approved",
    emailVerified: true,
    department: "Administration",
    designation: "System Administrator",
    location: "Headquarters",
    phoneNumber: "",
    qualifications: [],
    experience: [],
    skills: [],
    interests: [],
    certificates: [],
    createdAt: new Date().toISOString(),
  },
  {
    uid: "trainer-1",
    email: "trainer1@capacityconnect.in",
    displayName: "Alice Smith",
    role: "trainer",
    status: "approved",
    emailVerified: true,
    department: "Data Science Division",
    designation: "Senior Instructor",
    location: "Remote",
    phoneNumber: "",
    qualifications: [],
    experience: [],
    skills: [],
    interests: [],
    certificates: [],
    createdAt: new Date().toISOString(),
  },
  {
    uid: "trainer-2",
    email: "trainer2@capacityconnect.in",
    displayName: "Bob Jones",
    role: "trainer",
    status: "approved",
    emailVerified: true,
    department: "Software Engineering",
    designation: "Lead Trainer",
    location: "New York",
    phoneNumber: "",
    qualifications: [],
    experience: [],
    skills: [],
    interests: [],
    certificates: [],
    createdAt: new Date().toISOString(),
  },
  {
    uid: "trainee-1",
    email: "trainee1@capacityconnect.in",
    displayName: "Charlie Davis",
    role: "trainee",
    status: "approved",
    emailVerified: true,
    department: "Learners",
    designation: "Student",
    location: "Remote",
    phoneNumber: "",
    qualifications: [],
    experience: [],
    skills: [],
    interests: [],
    certificates: [],
    createdAt: new Date().toISOString(),
  },
  {
    uid: "trainee-2",
    email: "trainee2@capacityconnect.in",
    displayName: "Diana Prince",
    role: "trainee",
    status: "approved",
    emailVerified: true,
    department: "Learners",
    designation: "Student",
    location: "London",
    phoneNumber: "",
    qualifications: [],
    experience: [],
    skills: [],
    interests: [],
    certificates: [],
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: "course-1",
    code: "DS-101",
    title: "Introduction to Data Science",
    domain: "Data Science",
    description: "Learn the fundamentals of data science, including Python programming, pandas, and basic visualization.",
    trainerId: "trainer-1",
    trainerName: "Alice Smith",
    durationHours: 20,
    level: "Basic",
    syllabus: [
      "Python Basics",
      "Data Manipulation with Pandas",
      "Data Visualization with Matplotlib",
    ],
    enrolledTraineeIds: ["trainee-1"],
    rating: 4.8,
    reviewsCount: 12,
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80",
    createdAt: new Date().toISOString(),
  },
  {
    id: "course-2",
    code: "SE-201",
    title: "Advanced React Patterns",
    domain: "Software Engineering",
    description: "Deep dive into React hooks, state management, and performance optimization techniques.",
    trainerId: "trainer-2",
    trainerName: "Bob Jones",
    durationHours: 15,
    level: "Advanced",
    syllabus: [
      "Advanced Hooks (useMemo, useCallback)",
      "Context API and State Management",
      "Performance Optimization",
    ],
    enrolledTraineeIds: ["trainee-1", "trainee-2"],
    rating: 4.9,
    reviewsCount: 8,
    thumbnailUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&q=80",
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_QUIZZES: Quiz[] = [];
export const INITIAL_SUBMISSIONS: QuizSubmission[] = [];
export const INITIAL_RESOURCES: LibraryResource[] = [];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Welcome to the New CapacityConnect Platform",
    category: "circular",
    priority: "normal",
    content: "We are excited to launch our newly redesigned learning platform. Explore our catalog and start learning today!",
    publishedBy: "Platform Admin",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "ann-2",
    title: "New Course Available: Intro to Data Science",
    category: "course_spotlight",
    priority: "normal",
    content: "I have just published the Introduction to Data Science course. Enroll now to get started with Python and Pandas.",
    publishedBy: "Alice Smith",
    publishedAt: new Date().toISOString(),
  },
];

export const INITIAL_COMPETENCY_MAPPINGS: CompetencyMapping[] = [];
